# version: '3.9'  # Optional – can be removed

services:
  web:
    build: .
    command: python FileReader/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    working_dir: /code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - DJANGO_SETTINGS_MODULE=FileReader.FileReader.settings
      - DJANGO_URLS_MODULE=FileReader.FileReader.urls

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
